services:
  mysql:
    image: mysql:8.0
    container_name: mysql-cosmic-axiom
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: microservice_user
      MYSQL_PASSWORD: microservice_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
volumes:
  mysql_data:
