INSERT INTO FindingTemplate (
    id, title, description, recommendation, severity, reference, tags, createdAt, updatedAt
) VALUES
(UUID(), 'Unrestricted File Upload', 'The application allows users to upload arbitrary files without validation. This could be exploited to upload web shells or malicious scripts.', 'Implement server-side checks for MIME types, restrict allowed extensions, and store uploaded files outside the web root.', 'HIGH', 'CWE-434', JSON_ARRAY('web', 'upload', 'input-validation'), NOW(), NOW()),
(UUID(), 'Insecure Direct Object Reference (IDOR)', 'Sensitive objects (like user records) are accessible by changing a parameter value in the request URL or body.', 'Apply access control checks on every request using object ownership validation.', 'MEDIUM', 'CWE-639', JSON_ARRAY('authorization', 'api', 'web'), NOW(), NOW()),
(UUID(), 'SQL Injection', 'User input is improperly sanitized, allowing malicious SQL statements to be executed.', 'Use prepared statements or parameterized queries.', 'CRITICAL', 'CWE-89', JSON_ARRAY('database', 'input-validation', 'web'), NOW(), NOW()),
(UUID(), 'Cross-Site Scripting (XSS)', 'The application reflects unescaped input in responses, enabling malicious script injection.', 'Sanitize all output and use frameworks that auto-escape HTML.', 'HIGH', 'CWE-79', JSON_ARRAY('web', 'client', 'javascript'), NOW(), NOW()),
(UUID(), 'Weak Password Policy', 'The system allows weak or easily guessable passwords.', 'Enforce strong password complexity requirements.', 'LOW', 'CWE-521', JSON_ARRAY('authentication', 'policy'), NOW(), NOW()),
(UUID(), 'Missing Rate Limiting', 'The API allows unlimited login attempts, increasing the risk of brute-force attacks.', 'Implement rate limiting on sensitive endpoints.', 'MEDIUM', 'CWE-770', JSON_ARRAY('api', 'rate-limit', 'authentication'), NOW(), NOW()),
(UUID(), 'Exposed Sensitive Data in URL', 'Sensitive information is passed via query strings, which may be logged or cached.', 'Avoid including sensitive data in URLs; use POST body instead.', 'MEDIUM', 'CWE-598', JSON_ARRAY('privacy', 'api', 'url'), NOW(), NOW()),
(UUID(), 'Directory Traversal', 'The file path is constructed using unvalidated user input, allowing access to unauthorized files.', 'Sanitize input and use safe file path resolution methods.', 'HIGH', 'CWE-22', JSON_ARRAY('filesystem', 'input-validation'), NOW(), NOW()),
(UUID(), 'Hardcoded Credentials', 'Application contains hardcoded usernames or passwords.', 'Store credentials in environment variables or secure vaults.', 'CRITICAL', 'CWE-798', JSON_ARRAY('secrets', 'code', 'security'), NOW(), NOW()),
(UUID(), 'Improper Certificate Validation', 'The client does not validate SSL certificates properly.', 'Enable strict certificate validation and pin known certificates.', 'HIGH', 'CWE-295', JSON_ARRAY('ssl', 'encryption', 'client'), NOW(), NOW()),
(UUID(), 'Server Version Disclosure', 'The server exposes version information in HTTP headers.', 'Remove or obfuscate version headers.', 'LOW', 'CWE-200', JSON_ARRAY('information-disclosure', 'headers'), NOW(), NOW()),
(UUID(), 'No Session Timeout', 'User sessions do not expire after a period of inactivity.', 'Implement idle and absolute session expiration policies.', 'MEDIUM', 'CWE-613', JSON_ARRAY('session', 'timeout'), NOW(), NOW()),
(UUID(), 'CSRF Vulnerability', 'The application does not validate CSRF tokens on sensitive actions.', 'Implement CSRF tokens for all state-changing requests.', 'HIGH', 'CWE-352', JSON_ARRAY('csrf', 'web', 'state'), NOW(), NOW()),
(UUID(), 'Weak JWT Signing Key', 'JWT tokens are signed with a weak or guessable key.', 'Use strong, securely stored keys for token signing.', 'CRITICAL', 'CWE-345', JSON_ARRAY('jwt', 'authentication', 'crypto'), NOW(), NOW()),
(UUID(), 'Open Redirect', 'User can be redirected to arbitrary URLs via manipulated input.', 'Use a whitelist of allowed redirect destinations.', 'MEDIUM', 'CWE-601', JSON_ARRAY('redirect', 'web', 'input-validation'), NOW(), NOW()),
(UUID(), 'Lack of Audit Logging', 'The application does not log critical security events.', 'Implement centralized, tamper-evident audit logging.', 'LOW', 'CWE-778', JSON_ARRAY('logging', 'monitoring'), NOW(), NOW()),
(UUID(), 'Insufficient Transport Layer Protection', 'Sensitive data is transmitted without encryption.', 'Enforce HTTPS and disable insecure HTTP endpoints.', 'CRITICAL', 'CWE-319', JSON_ARRAY('tls', 'https', 'encryption'), NOW(), NOW()),
(UUID(), 'Use of Deprecated Cryptographic Algorithms', 'The application uses outdated or insecure crypto functions.', 'Replace with current, secure cryptographic algorithms.', 'HIGH', 'CWE-327', JSON_ARRAY('encryption', 'crypto'), NOW(), NOW()),
(UUID(), 'Unauthenticated Debug Console', 'A debug interface is exposed without authentication.', 'Disable debug endpoints in production.', 'HIGH', 'CWE-215', JSON_ARRAY('debug', 'exposure', 'security'), NOW(), NOW()),
(UUID(), 'Improper Input Validation', 'User input is not validated or sanitized before processing.', 'Apply strict input validation and encoding.', 'MEDIUM', 'CWE-20', JSON_ARRAY('input-validation', 'security', 'api'), NOW(), NOW());
